### ISSUE TITLE
Ability to format on save

### ISSUE THREAD

**Issue by markst** [vknabel/vscode-swiftlint#43]
#40 means we are able to fix lint errors on save.

I like to be able to format my documents using `swiftlint` as well:
```
swiftlint --fix --format
```

Might it be of interest to add formatting as an option as well as `fixAll`?

**Comment by markst** [comment]
Relevant lines in my `.swiftlint.yml`:

```yaml
indentation: 2

indentation_width:
  indentation_width: 2
```
